---
overwrite: false
defaults:
    GRUB_DEFAULT: "0"
    GRUB_TIMEOUT: 5
    GRUB_ENABLE_CRYPTODISK: true
    GRUB_DISTRIBUTOR: "Vital OS"
    GRUB_THEME: "/usr/share/grub/themes/vital/theme.txt"
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet splash"
