---
backend: apt
update_db: false
operations:
    - try_remove:
          - calamares
          - casper
          - discover
          - laptop-detect
          - user-setup
          - squashfs-tools
          - grub-efi-amd64-signed
          - shim-signed
          - libqt5svg5
          - qml-module-qtquick2
          - qml-module-qtquick-window2
          - qml-module-qtgraphicaleffects
