---
defaultFileSystemType: "ext4"
initialPartitioningChoice: none
initialSwapChoice: none
drawNestedPartitions: false
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 512MiB
    minimumSize: 100MiB
    label: "VITAL_EFI"
userSwapChoices:
    - none
    - small
    - file
luksGeneration: luks1
