---
dontChroot: false
timeout: 60
script:
    - "rm -f /etc/sudoers.d/casper"
    - "rm -f /usr/share/applications/vitalos-install.desktop"
    - "rm -f /etc/xdg/autostart/vitalos-installer.desktop"
    - "rm -f /etc/polkit-1/rules.d/49-vitalos-installer.rules"
    - "rm -f /usr/share/initramfs-tools/scripts/casper-bottom/26vitalos_desktop"
    - "rm -f /usr/libexec/vitalos-install-check"
    - "rm -f /usr/libexec/vitalos-install-bootloader"
