---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false
geoip:
    style: "none"
requirements:
    requiredStorage: 16
    requiredRam: 2
    check:
        - storage
        - ram
        - power
        - root
    required:
        - storage
        - ram
        - root
