---
modules-search: [ local ]

instances:
- id: vital-prepare
  module: shellprocess
  config: shellprocess_vital_prepare.conf
- id: vital-cleanup
  module: shellprocess
  config: shellprocess_vital_cleanup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - shellprocess@vital-prepare
  - packages
  - initramfscfg
  - initramfs
  - grubcfg
  - bootloader
  - shellprocess@vital-cleanup
  - umount
- show:
  - finished

branding: vitalos
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
